# Generated by Django 4.1 on 2023-08-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_image_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='marker',
            field=models.CharField(default='undefined', max_length=100, unique=True),
        ),
    ]
