# Generated by Django 4.1 on 2023-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_image_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
