# Generated by Django 4.1 on 2023-11-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_image_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
