# Generated by Django 4.1 on 2023-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0006_image_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkerTxtPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marker", models.CharField(default="undefined", max_length=100)),
                (
                    "txt_path",
                    models.FileField(blank=True, null=True, upload_to="static/txt/"),
                ),
            ],
        ),
    ]
